{% set name = "pyrobex" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ed5a927e9a2204151e11b20a3b723cbc930e7b337164a54c544a49cc0ab6830

build:
  number: 0
  noarch: python
  entry_points:
    - robex=pyrobex.cli:main
  script:
    - rm -rf ./pyrobex/ROBEX
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nibabel
    - numpy
    - python >=3.6

test:
  imports:
    - pyrobex
  commands:
    - pip check
    - robex --help
  requires:
    - pip

about:
  home: https://github.com/jcreinhold/pyrobex
  summary: python bindings for ROBEX brain extraction
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://pyrobex.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sarthakpati
